version: "3.5"
services:
  mongo1:
    image: mongo:3.4
    #volumes:
    #  - ./p:/data
    env_file:
      - ./mongo-repl.env
    ports:
      - "27017:27017"
    command: mongod  --replSet apprepl 
    networks:
      - app-network
  mongo2:
    image: mongo:3.4
    #volumes:
    #  - ./s1:/data
    ports:
      - "27018:27017"
    command: mongod  --replSet apprepl
    networks:
      - app-network
  mongo3:
    image: mongo:3.4
    #volumes:
    #  - ./s2:/data
    ports:
      - "27019:27017"
    command: mongod  --replSet apprepl
    networks:
      - app-network
  postgres-server:
    image: postgres:latest
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    env_file:
      - .env_db_pgsql
    networks:
      - app-network
    #environment:
    #  - POSTGRES_DB=zabbix
    #  - POSTGRES_USER=zabbix
    #  - POSTGRES_PASS=simplepasswd
    #  #- POSTGRES_ROOT_PASSWORD=simplepasswd
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-3.4-latest
    ports:
      - "9090:80"
      - "10051:10051"
    #volumes:
      #- /etc/localtime:/etc/localtime:ro
      #links:
      #li- zabbix-db:zabbix.db
    networks:
      - app-network
    depends_on:
      - postgres-server
    env_file:
      - .env_db_pgsql

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-3.4-latest
    ports:
      - "8081:80"
      - "8443:443"
    links:
      - postgres-server:postgres-server
      - zabbix-server:zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
    env_file:
      - .env_db_pgsql
    #  - .env_web
    user: root
    depends_on:
      - postgres-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      app-network:
        #aliases:
        #  - zabbix-web-nginx-pgsql
        #  - zabbix-web-nginx-alpine-pgsql
        #  - zabbix-web-nginx-pgsql-alpine
      #zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "alpine"
networks:
  app-network:
    driver: bridge
